CREATE SEQUENCE SEQ_EMPRESAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_EMPRESAS (
    PRIMARY KEY (ID_EMPRESA),
    ID_EMPRESA INTEGER DEFAULT SEQ_EMPRESAS.NEXTVAL NOT NULL,
    NOME_EMPRESA VARCHAR2(100) NOT NULL,
    ENDERECO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
    HORA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
