CREATE SEQUENCE SEQ_SOLICITACAO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_SOLICITACAO_COLETA (
    PRIMARY KEY (ID_SOLICITACAO),
    ID_EMPRESA INTEGER NOT NULL,
    CONSTRAINT FK_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TBL_EMPRESAS (ID_EMPRESA),
    ID_COOPERATIVA INTEGER NOT NULL,
    CONSTRAINT FK_COOPERATIVA FOREIGN KEY (ID_COOPERATIVA) REFERENCES TBL_COOPERATIVAS (ID_COOPERATIVA),
    ID_SOLICITACAO INTEGER NOT NULL,
    DESCRICAO_MATERIAL VARCHAR2(200) NOT NULL,
    ENDERECO_SOLICITACAO VARCHAR2(200) NOT NULL,
    STATUS_SOLICITACAO VARCHAR2(100) NOT NULL,
    DESCRICAO_NOTIFICACAO VARCHAR2(100) NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
    HORA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);