CREATE SEQUENCE SEQ_USUARIOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USUARIOS (
    USUARIO_ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER',
    DATA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    HORA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);